version: '3.8'

services:
  mariadb:
    image: 'mariadb:10.11.2'
    restart: always
    environment:
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    ports:
      - ${MARIADB_LOCAL_PORT}:${MARIADB_DOCKER_PORT}
    volumes:
      - db:/var/lib/mysql

  app:
    depends_on:
      - mariadb
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}

volumes:
  db: