version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    privileged: true
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}
    volumes:
      - /var/run/dbus/:/var/run/dbus/:z
      - ./misensormonitorsystem.sqlite:${SQLITE_FILE_PATH}
    command: sh -c 'npm run migrate && npm run start'
